#!/bin/sh
# Guest-Wi-Fi only. Installs a home-folder compiler + pkg-config + Wayland
# headers, a Python venv, and Cargo crate sources. No sudo.
#
# After this finishes: airplane mode, then ./BUILD.sh
set -e
cd "$(dirname "$0")"
root="$PWD"
prefix="${SKATE_DECK_PREFIX:-$HOME/ccenv}"
envfile="$root/.deck-env"

die() { echo "setup.sh: $*" >&2; exit 1; }

echo "=== 1/5 rustup (needs 1.85+ for edition 2024) ==="
if ! command -v rustup >/dev/null 2>&1; then
    if [ ! -x "$HOME/.cargo/bin/rustup" ]; then
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
    fi
fi
# shellcheck disable=SC1091
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
command -v rustc >/dev/null 2>&1 || die "rustc not on PATH after rustup"
rustup toolchain install stable
rustup default stable
echo "rustc $(rustc --version)"

echo "=== 2/5 micromamba toolchain in $prefix (no sudo) ==="
micromamba=""
for candidate in \
    "${MAMBA_EXE-}" \
    "$HOME/bin/micromamba" \
    "$HOME/micromamba" \
    "$prefix/bin/micromamba" \
    "$(command -v micromamba 2>/dev/null || true)"
do
    if [ -n "$candidate" ] && [ -x "$candidate" ]; then
        micromamba="$candidate"
        break
    fi
done
if [ -z "$micromamba" ]; then
    mkdir -p "$HOME/bin"
    curl -L https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xjv -C "$HOME" bin/micromamba
    micromamba="$HOME/bin/micromamba"
    [ -x "$micromamba" ] || die "failed to unpack micromamba to $HOME/bin/micromamba"
fi
pkgs="compilers gcc gxx binutils clang clangxx libclang pkg-config wayland libxkbcommon libxcb alsa-lib eudev"
if [ ! -d "$prefix/conda-meta" ]; then
    "$micromamba" create -y -p "$prefix" -c conda-forge $pkgs
else
    "$micromamba" install -y -p "$prefix" -c conda-forge $pkgs
fi

echo "=== 3/5 write $envfile ==="
pc_path="$prefix/lib/pkgconfig:$prefix/share/pkgconfig"
{
    echo "# Generated by setup.sh. Sourced by BUILD.sh. Not for airplane-mode network."
    echo "export PATH=\"$prefix/bin:\$HOME/.cargo/bin:\$PATH\""
    echo "export CC=\"$prefix/bin/cc\""
    echo "export CXX=\"$prefix/bin/c++\""
    echo "export PKG_CONFIG=\"$prefix/bin/pkg-config\""
    echo "export PKG_CONFIG_PATH=\"$pc_path\""
    echo "export LIBCLANG_PATH=\"$prefix/lib\""
} > "$envfile"
# Prefer gcc as `cc` if the prefix has no cc symlink.
if [ ! -x "$prefix/bin/cc" ] && [ -x "$prefix/bin/gcc" ]; then
    printf 'export CC="%s/bin/gcc"\nexport CXX="%s/bin/g++"\n' "$prefix" "$prefix" >> "$envfile"
fi
# shellcheck disable=SC1090
. "$envfile"
command -v cc >/dev/null 2>&1 || die "cc still missing after toolchain install"
command -v pkg-config >/dev/null 2>&1 || die "pkg-config still missing"
pkg-config --exists wayland-client || die "wayland-client.pc missing (pkg-config path=$PKG_CONFIG_PATH)"
echo "cc=$(command -v cc)"
echo "pkg-config=$(command -v pkg-config)"

echo "=== 4/5 Python venv for later asset conversion ==="
if [ ! -x "$root/.venv/bin/python" ]; then
    python3 -m venv "$root/.venv"
fi
"$root/.venv/bin/pip" install -q numpy==2.2.6 Pillow==11.3.0

echo "=== 5/5 cargo fetch --locked (crate sources only; no Steam build) ==="
cargo fetch --locked

echo
echo "setup.sh finished."
echo ">>> AIRPLANE MODE NOW (disable Wi-Fi)."
echo ">>> Then:  ./BUILD.sh"
echo ">>> PLAY.sh needs SKATE_ASSETS after you convert an Xbox 360 default.xex (not a PS3 ISO)."
